### ISSUE TITLE
Try in REPL broken for R.isEmpty

### ISSUE THREAD

**Issue by pm-radu** [selfrefactor/rambda#220]
On the README page there is a link to the REPL so you can try `.isEmpty`. If I go to that page I get an error:

![image](https://user-images.githubusercontent.com/46872903/61910447-d37b5880-af88-11e9-92a6-8c6cb47213fe.png)

**Comment by selfrefactor** [comment]
This is because REPL is had not been updated in the last month. Will be fixed in 2 days.

**Comment by selfrefactor** [comment]
I updated the version but `R.isEmpty` is still missing. The reason is that the REPL is used by both `Rambda` and its extended version `Rambdax`. `R.isEmpty` is one of the methods recently added to `Rambda` not by me but a contributor. While I agree on his reasoning to add these methods, I prefer not to transfer them to `Rambdax` and this is the reason why the issue will still exists.

I will close the issue as I did the best I could - I removed the REPL link from `R.isEmpty` documentation.
