### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by makarkotlov** [selfrefactor/rambda#250]
Is it possible somehow to get IE11 support?

**Comment by selfrefactor** [comment]
After Rambda moved to `rollup` it is no longer possible as far as I know.

We can try edit `rollup` config in order to transpile for IE11:

https://github.com/selfrefactor/rambda/blob/master/files/rollup.config.js

You can try, but I am not big fan because as more time passes, the less need is for IE support.
I will close the ticket, but feel free to reopen it, if you can solve `rollup` config.

**Comment by selfrefactor** [comment]
Can you share what is not working with IE11 as Ubuntu user I have no access to this browser.

**Comment by makarkotlov** [comment]
There are arrow functions and other goodies in rambda which IE doesn't support. I have tried to replace ramda with rambda in our project but suddenly we lost IE11 support

**Comment by selfrefactor** [comment]
Thanks. I might try to solve this later, but let us leave it closed for the time being.

**Comment by opsidao** [comment]
@selfrefactor FYI, Microsoft provides VM images with any version of IE/Edge for this kind of testing (free of charge): https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
