### ISSUE TITLE
Typings from v6.0.0 are incompatible with immutable arrays

### ISSUE THREAD

**Issue by G07cha** [selfrefactor/rambda#547]
Due to changes in https://github.com/selfrefactor/rambda/commit/03b8e7c818eba5780dbe6021a1a562ddf920390d functions accepting array are now only accept mutable arrays or cloned immutable arrays, I've noticed that in many functions arrays are being cloned internally, is there a reason for this change?

**Comment by selfrefactor** [comment]
It was a bit naive change, as the reasoning was the readability of `files/index.d.ts` file. There was lack of consistency as many arrays was missing `readonly` and it was easier for me delete `readonly`, instead of fixing it. Also, I thought that `readonly` may be obsolete in functional programming context.

Now, I realize that I was wrong thinging and I will add `readonly` to all arrays in the same way `@types/ramda` does. Will release a fix this weekend it this in upcoming `6.2.0`

**Comment by selfrefactor** [comment]
It took me longer than expected, but the version `6.2.0` fixes this issue, so I am closing it.

**Comment by G07cha** [comment]
Can confirm, thanks!
