### ISSUE TITLE
Currying and TypeScript

### ISSUE THREAD

**Issue by ivan-kleshnin** [selfrefactor/rambda#548]
I'm a Typescript newbie... As it seems, `R.curry` function does not preserve typing at all (returning `any`). I suppose this is due to TypeScript limitations on generics and variadic args. Would be great if you enlighten us on the current status quo of this topic. 

Looks like TypeScript 4 has all the ingredients for generic `curry`. Are you going to update as it leaves beta? 

Are there some workarounds to make curried and strictly typed functions (with or without `R.curry`) right now?

**Comment by selfrefactor** [comment]
Unfortunately, there is not much to share. I was subscribed to [variadic functions Typescript issue](https://github.com/microsoft/TypeScript/issues/5453) so I have the change to play very early on with **variadic tuple types**. I also read all the discussions and examples around it in the hope that I will be able to use it in *Rambda*. As much as I tried, I couldn't make it work. 

Now, there is not much I can do, so I am just hoping that maintainers of `@types/ramda` to take advantage of this new TS feature. Other option is to open Stackoverflow question, but as much as I read about currying in the context of **variadic tuple types**, this feature alone is not enough and further features are needed in order to receive proper definitions. Still, I will open the question and provide a link, once I do that.

**Comment by ivan-kleshnin** [comment]
Ok, a got the situtation, thanks for sharing! 

I discovered, for myself, that I'm fine with `(x: a) => x(b) : c` kind of typings. They are a piece of cake to type comparing to variadic and while they require to call functions like `fn(x)(y)` instead of `fn(x, y)` that is such a minor detail in overall picture so it's probably not worth fighting against. A significant % of functions I write are composed with `R.pipe` anyway so I don't see a difference. 

Guys from https://github.com/sanctuary-js/sanctuary came to the same conclusion and now I certainly see how.

**Comment by selfrefactor** [comment]
I, myself barely use `R.curry`, so you have deeper insights what typings works best.
So, you don't mind the current `R.curry` typings? If so, then you wouldn't mind closing this issue, as I promise to update `R.curry` once `@types/ramda` make any change to it.

**Comment by ivan-kleshnin** [comment]
Sure, I simply wanted to know your opinion. Thanks again.
