### ISSUE TITLE
R.none incorrectly returns true

### ISSUE THREAD

**Issue by dizney** [selfrefactor/rambda#625]
```
const result = R.none((input) => input > 1, [1, 2, 3]);
```

Would expect false as result but it is true. It seems like none returns true when *any* value in the list returns false instead of all.

**Comment by selfrefactor** [comment]
Thank you so much for this issue. It is a big error, so I will try to make a release asap.

**Comment by selfrefactor** [comment]
I am closing the issue as a fix is released with `7.0.3`. Again, thank you for taking the time to report this.

**Comment by dizney** [comment]
Thanks for the quick fix Dejan! 👍

**Comment by selfrefactor** [comment]
Just last note as this is serious mistake - the wrong logic was introduced with version `7.0.0`, i.e. before that the method was working correctly. Also I found that there was an error in the script that checks Rambda methods against Ramda tests, so again thank you for spotting this out as it would otherwise go unnoticed.
