### ISSUE TITLE
[BUG] Remove the SRC and Readme from dist folder

### ISSUE THREAD

**Issue by patrickalima98** [selfrefactor/rambda#724]
**Describe the bug**
I'm using this library with a serverless environment, with Deno Deploy and it's working great!
But I noticed that there are some unnecessary folders and files in the npm published version. These files are:

-src
-CHANGELOG.md
- README.md

The main problem with this is that the README.md is 450 KB and the SRC folder is 83 KB. Since serverless is cold start, the final library storage size is 854 KB, very close to 1 MB!

So I would like to know if it is possible to ignore these folders and files in upcoming and future versions of rambda to help improve performance on serverless platforms like Deno Deploy, as the size of each library contributes to cold start.

**Context(which version of library)**
9.1.0

**Comment by patrickalima98** [comment]
Edit: If necessary, I can open a PR, let me know!

**Comment by selfrefactor** [comment]
Thanks for opening this issue. I will try to use DenoDeploy for myself to see what can be done so that the main release structure remains the same.
if there is `.denoignore`, that could help. `src` files are good to have as it allows same release for web and node so we'll have to think how to make Deno specific release, maybe if it possible to release from a branch different than `master`.

I am open to manual action, i.e. no need to have a automated procedure for this.

**Comment by selfrefactor** [comment]
I will remove `Readme.md` in general as this makes sense.
I can also make modified version of `package.json` in release such as `9.2.0-for-node-lambda' where only `dist` folder will be declared. That should solve the issue.

**Comment by selfrefactor** [comment]
I think that moving forward, such process is hard to support, so I will close the issue.
