### ISSUE TITLE
index accumulates when addIndex is put inside pipe

### ISSUE THREAD

**Issue by ywchan2005** [selfrefactor/rambda#85]
when addIndex is composed by pipe
```
const foo = R.pipe(
  R.addIndex(R.map)((x, idx) => x+'-'+idx),
)
```

indices (i.e. idx) received are correct in the first call
```
console.log(foo(['a', 'b', 'c', 'd']))
// => ['a-0', 'b-1', 'c-2', 'd-3']
```

however, indices seem to accumulate in the second call
```
console.log(foo(['a', 'b']))
// => ['a-4', a-5']
```

and also in later calls
```
const result = foo(['a', 'b', 'c'])
// => ['a-6', 'b-7', 'c-8']
```

[sample code](https://rambda.now.sh/?const%20foo%20=%20R.pipe(%0A%20%20R.addIndex(R.map)((x,%20idx)%20=%3E%20x+%27-%27+idx)%0A)%0A%0Aconsole.log(foo([%27a%27,%20%27b%27,%20%27c%27,%20%27d%27]))%0Aconsole.log(foo([%27a%27,%20%27b%27]))%0Aconst%20result%20=%20foo([%27a%27,%20%27b%27,%20%27c%27])%0Aconsole.log(result))

**Comment by selfrefactor** [comment]
So this method `addIndex` is not added by me, rather than from a contributor. As much I can see, I cannot solve it in simple way, so I will go end remove it. 

New version will be published in the coming days, so you still have time to suggest solution and in this case the new version will contain your code.
